Models/ErrorViewModel.cs
using System;

namespace SqrRootWebApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/CalcController.cs
using System;
using Microsoft.AspNetCore.Mvc;

namespace SqrRootWebApp.Controllers {
    public class CalcController : Controller {

        [HttpGet]
        public ActionResult SqrRoot () {
            return View ();
        }

        [HttpPost]
        public ActionResult SqrRoot (string firstNumber, string secondNumber) {

            int numeroOne = int.Parse (firstNumber);
            int numeroTwo = int.Parse (secondNumber);

            int firstRoot = Convert.ToInt32 (Math.Sqrt (numeroOne));
            int secondRoot = Convert.ToInt32 (Math.Sqrt (numeroTwo));

            string result = "";

            if (firstRoot > secondRoot) {
                result = ("The number " + numeroOne + " with Square root " + firstRoot + " has a higher square root than the number " + numeroTwo + " with square root " + secondRoot);
            } else if (secondRoot > firstRoot) {
                result = ("The number " + numeroTwo + " with Square root " + secondRoot + " has a higher square root than the number " + numeroOne + " with square root " + firstRoot);
            } else if (firstRoot == secondRoot) {
                result = ("The number " + numeroTwo + " with Square root " + secondRoot + " has the same square root as the number " + numeroOne + " with square root " + firstRoot + ". \n\nPlease enter another set of values. Try inputting different numbers.");
            }
            //} else if (int.TryParse (secondNumber, out numeroTwo)) {
            //    int firstRoot = Convert.ToInt32 (Math.Sqrt (numeroOne));
            //    int secondRoot = Convert.ToInt32 (Math.Sqrt (numeroTwo));

            //    if (numeroTwo > numeroOne) {
            //        result = ("The number " + numeroTwo + " with Square root " + secondRoot + " has a higher square root than the number " + numeroOne + " with square root " + firstRoot);
            //        //} else if (numeroTwo > numeroOne) {
            //        //    result = ("The number " + numeroTwo + " with Square root " + secondRoot + "has a higher square root than the number " + numeroOne + " with square root " + firstRoot);
            //    }
            //} else {
            //    result = ("\nThat is not a number. \nPlease check your input and ensure it is a number");
            //}

            ViewBag.Result = result;
            return View ();
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SqrRootWebApp.Models;

namespace SqrRootWebApp.Controllers {
    public class HomeController : Controller {
        private readonly ILogger<HomeController> _logger;

        public HomeController (ILogger<HomeController> logger) {
            _logger = logger;
        }

        public IActionResult Index () {
            return View ();
        }

        public IActionResult Privacy () {
            return View ();
        }

        [ResponseCache (Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error () {
            return View (new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Calc/SqrRoot.cshtml
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SQR.ROOT.WebApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="current">
                            <a class="nav-link, current" asp-area="" asp-controller="Calc" asp-action="SqrRoot">Sqr.Root.Calculator</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

@{
    ViewData["Title"] = "Square-Root Calculator";
}

<div class="text-center">
<h1 class="display-4">@ViewData["Title"]</h1>

<p>Input your 'First Number' and 'Second Number' in the boxes below to carryout the Square-Root Calculation.</p>


<div>
    <form asp-controller="Calc" asp-action="SqrRoot" method="POST">
    <input type="number" placeholder="First Number" name="firstNumber" /><br/>
    <input type="number" placeholder="Second Number" name="secondNumber" /><br/>
    <button name="Submit">Submit</button>
    </form>
</div>
<br>
@if(ViewBag.Result != null) {
    <div>
        <p>@ViewBag.Result </p>
    </div>
}

Views/Home/Index.cshtml
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SQR.ROOT.WebApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="current">
                            <a class="nav-link, current" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Calc" asp-action="SqrRoot">Sqr.Root.Calculator</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <br>
    <p>Thank you for using the Square-Root Comparison App by Benjamin (Bhenjameen).</p>
<br>
<br>
    <h4>HOW IT WORKS</h4>
    <p>The Square-Root WebApp takes two (2) numbers separately,<br> calulates their square-roots, further determines which<br> number has the higher square-root and outputs the result.</p>
<br>
<p>Click <a asp-controller="Calc" asp-action="SqrRoot">here to go to the Sqr.Root.Comparison.Calculator</a></p>
<br>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en-US">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SqrRootWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - SqrRootWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>